# Generated by Django 5.0.4 on 2024-04-16 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0002_client_owner_mailing_owner_message_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('image', models.ImageField(upload_to='blog_images/')),
                ('views', models.IntegerField(default=0)),
                ('publish_date', models.DateField()),
            ],
        ),
    ]
